In [33]:
import pandas as pd
import numpy as np
import seaborn as sns

## Cleaning Tasks

1) Drop columns 'nameOrig', 'nameDest','isFlaggedFraud', 'oldbalanceDest', 'newbalanceOrig', 'newbalanceDest', and 'step'

## Create Features:
1) 'trans_perc'
2) 'had_zero_orig_balance'
3) 'is_cash_out'
4) 'is_transfer'
5) 'new_balance_orig_0'

In [34]:
df = pd.read_csv('../data/activity_records.csv')
df = df.drop(columns=['step', 'nameOrig', 'nameDest','isFlaggedFraud', 'oldbalanceDest', 'newbalanceDest'])
df.head()

       type    amount  oldbalanceOrg  newbalanceOrig  isFraud
0   PAYMENT   9839.64       170136.0       160296.36        0
1   PAYMENT   1864.28        21249.0        19384.72        0
2  TRANSFER    181.00          181.0            0.00        1
3  CASH_OUT    181.00          181.0            0.00        1
4   PAYMENT  11668.14        41554.0        29885.86        0

In [35]:
# Create New Features
df['trans_perc'] = df['amount'] / df['oldbalanceOrg'].replace(0, np.nan)
df['trans_perc'] = df['trans_perc'].fillna(0)

df['had_zero_orig_balance'] = (df['oldbalanceOrg'] == 0).astype(int)

df['is_cash_out'] = (df['type'] == 'CASH_OUT').astype(int)
df['is_transfer'] = (df['type'] == 'TRANSFER').astype(int)
df = df.drop(columns=['type'])

df['new_balance_orig_0'] = (df['newbalanceOrig'] == 0).astype(int)
df = df.drop(columns=['newbalanceOrig'])

df.head()

,amount,oldbalanceOrg,isFraud,trans_perc,had_zero_orig_balance,is_cash_out,is_transfer,new_balance_orig_0
0,9839.64,170136.0,0,0.057834,0,0,0,0
1,1864.28,21249.0,0,0.087735,0,0,0,0
2,181.00,181.0,1,1.000000,0,0,1,1
3,181.00,181.0,1,1.000000,0,1,0,1
4,11668.14,41554.0,0,0.280795,0,0,0,0

In [36]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6362620 entries, 0 to 6362619
Data columns (total 8 columns):
 #   Column                 Dtype
---  ------                 -----
 0   amount                 float64
 1   oldbalanceOrg          float64
 2   isFraud                int64
 3   trans_perc             float64
 4   had_zero_orig_balance  int64
 5   is_cash_out            int64
 6   is_transfer            int64
 7   new_balance_orig_0     int64
dtypes: float64(3), int64(5)
memory usage: 388.3 MB

In [38]:
# Double check for any resulting near perfect correlations.
print(df[features].corr())

                         amount  oldbalanceOrg  trans_perc  \
amount                 1.000000      -0.002762    0.036067
oldbalanceOrg         -0.002762       1.000000   -0.006936
trans_perc             0.036067      -0.006936    1.000000
had_zero_orig_balance  0.039323      -0.202825   -0.016905
new_balance_orig_0     0.115566      -0.323722    0.011358
is_cash_out           -0.004376      -0.200899    0.003166
is_transfer            0.365896      -0.081593    0.024088

                       had_zero_orig_balance  new_balance_orig_0  is_cash_out  \
amount                              0.039323            0.115566    -0.004376
oldbalanceOrg                      -0.202825           -0.323722    -0.200899
trans_perc                         -0.016905            0.011358     0.003166
had_zero_orig_balance               1.000000            0.604440     0.200448
new_balance_orig_0                  0.604440            1.000000     0.475586
is_cash_out                         0.200448            0.475586     1.000000
is_transfer                         0.128686            0.239469    -0.222672

                       is_transfer
amount                    0.365896
oldbalanceOrg            -0.081593
trans_perc                0.024088
had_zero_orig_balance     0.128686
new_balance_orig_0        0.239469
is_cash_out              -0.222672
is_transfer               1.000000

In [40]:
df.to_csv('../data/cleaned_activity_data.csv', index=False)